### ISSUE TITLE
UI header not working on iPad portrait mode

### ISSUE THREAD

**Issue by wiseman** [wiseman/mavelous#10]
It works fine in landscape mode.

See http://imgur.com/a/vY1D4

Actually I just checked and you can see the same thing in a desktop browser window that's been made narrow.

**Comment by pchickey** [comment]
Thanks, I've only tested it with landscape mode. This is a problem with the Bootstrap UI's navbar  - I'll look into ways to disable the dropdown menu behavior.

**Comment by wiseman** [comment]
It seems like there should be enough space to fit it all in even in portrait mode.

**Comment by pchickey** [comment]
Specifically, this is due to bootstrap-responsive.css applying a rule to
the .nav-collapse div when the @media (max-width: 979px) becomes true.

I don't think we need a collapsing nav bar - I'll get rid of the nav
collapse div.

On Mon, Jul 30, 2012 at 10:16 AM, John Wiseman <
reply@reply.github.com
