### ISSUE TITLE
Map not clickable when using Kindle Fire HD in any browser tested (Opera, SIlk)

### ISSUE THREAD

**Issue by overlordsc** [wiseman/mavelous#23]
Ordered a kindle fire hd to use with mavelous.. it seems to be plenty fast but when you try and double click on the map it does nothing (no blue marker). 

I have tried this in opera and the default "silk" browser.

I went to bing maps to try a double click and it seems to zoom in with no issue.

Any help is appreciated.

Thanks!

**Comment by pchickey** [comment]
Thanks for reporting this bug. Unfortunately I don't own a Kindle Fire HD
to reproduce, but the mapping layer is in the middle of being revamped and
this behavior may change (for better or worse) soon. I'll ping you when the
new Leaflet.js based mapping is pushed to master. In the meantime, could
you evaluate the following Leaflet example web page and tell us how all of
the touch inputs work?

http://leafletjs.com/examples/mobile-example.html

FWIW, I started doing some testing on my iPad again after ignoring it for
some time, and found some issues there I'll be working on soon. At the
moment, anything other than Chrome on the desktop may be a bit spotty.

**Comment by overlordsc** [comment]
I just tried the URL map, thanks for the quick reply.
The behavior looks fine as far as double tap to zoom in. The specific behavior that is not working within mavelous is dropping a pin. If you have an example using the leafletjs in that manner I would be happy to try it out!

**Comment by pchickey** [comment]
The leaflet rewrite is mostly finished as of tonight, aside from some bugs which only exist when the PFD is instantiated. You can please test the new map here. It should support double tap to make the guide point. So far it seems to me to work much better on iOS than the existing modestmaps code works.

http://moreproductive.org/mavelous_web/leafletbranch/leaflet.html

**Comment by overlordsc** [comment]
The new code works well for the pin drop on the fire! It also seems to improve the pin drop on htc Evo 4g (1st gen) phone tho sometimes the map zooms instead of dropping a pin (just on phone). Very exciting.. is this going to make it into a distribution update today or can I get a zip from you and work it in my self for further testing here? Again MUCH APPRECIATED!

**Comment by overlordsc** [comment]
On another note I noticed that the leafletbranch folks have openmaps integration. I am very interested in using an offline cache for maps when using the new code. Looks like we can get the north america maps here: http://download.geofabrik.de/openstreetmap/

Is this functionality going to be left in as a map provider option or?

**Comment by pchickey** [comment]
Good to hear. The new map code will make it into the main distribution
shortly - I need to merge with John's work in master and find a fix for
integration with the PFD. Should be able to do both of those this week.

The map should not zoom on double tap- if I can reproduce this I'll have to
file a bug with Leaflet.

Pat

On Nov 28, 2012, at 7:52 AM, overlordsc notifications@github.com wrote:

The new code works well for the pin drop on the fire! It also seems to
improve the pin drop on htc Evo 4g (1st gen) phone tho sometimes the map
zooms instead of dropping a pin (just on phone). Very exciting.. is this
going to make it into a distribution update today or can I get a zip from
you and work it in my self for further testing here? Again MUCH APPRECIATED!

—
Reply to this email directly or view it on
GitHubhttps://github.com/wiseman/mavelous/issues/23#issuecomment-10807636.

**Comment by pchickey** [comment]
We can provide caching of OSM tiles on the mavelous server without much
trouble. Deploying a tile server that operates on the downloadable binary
data may be more difficult. Ill look into this soon.

On Nov 28, 2012, at 7:56 AM, overlordsc notifications@github.com wrote:

On another note I noticed that the leafletbranch folks have openmaps
integration. I am very interested in using an offline cache for maps when
using the new code. Looks like we can get the north america maps here:
http://download.geofabrik.de/openstreetmap/

Is this functionality going to be left in as a map provider option or?

—
Reply to this email directly or view it on
GitHubhttps://github.com/wiseman/mavelous/issues/23#issuecomment-10807802.
